services:
  mysql:
    image: mysql:8.0
    container_name: ongea_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ongea_task_db
      MYSQL_USER: ongea_admin
      MYSQL_PASSWORD: ongeapassword
    ports:
      - "3306:3306"
    volumes:
      - ongea_mysql_data:/var/lib/mysql

volumes:
  ongea_mysql_data:
