"""Add motivation cache fields to user

Revision ID: 014c873baaa6
Revises: 4bb377dfbb61
Create Date: 2026-04-13 08:43:15.436464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014c873baaa6'
down_revision = '4bb377dfbb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Columns already added by previous migration; skipping to avoid duplicate column error

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('motivation_date')
        batch_op.drop_column('motivation_message')

    # ### end Alembic commands ###
