"""Added due_date and category_id to task

Revision ID: 2a58c0ace2c6
Revises: afe18bc94018
Create Date: 2026-05-09 22:38:44.460205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a58c0ace2c6'
down_revision = 'afe18bc94018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('due_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('category')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_regen_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_regen_count', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=50), server_default=sa.text("'General'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('due_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
