"""Adds notification fields

Revision ID: 45d63c68832b
Revises: 5cba15b1664a
Create Date: 2026-05-16 15:00:54.629421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d63c68832b'
down_revision = '5cba15b1664a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dismissed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_dismissed')

    # ### end Alembic commands ###
