"""Add category color and category name to Task model

Revision ID: 7d7126740a4f
Revises: 014c873baaa6
Create Date: 2026-05-16 11:20:11.735864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7126740a4f'
down_revision = '014c873baaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('category_name')
        batch_op.drop_column('category_color')

    # ### end Alembic commands ###
