"""Added motivation message to user

Revision ID: 92e494566c59
Revises: 4bb377dfbb61
Create Date: 2026-04-25 10:06:34.294496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e494566c59'
down_revision = '4bb377dfbb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivation_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('motivation_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('motivation_date')
        batch_op.drop_column('motivation_message')

    # ### end Alembic commands ###
