"""Initial migration

Revision ID: c974c4ad11f7
Revises: 
Create Date: 2026-05-25 03:24:06.602455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c974c4ad11f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create user table first
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('username', sa.String(length=80), unique=True, nullable=False),
        sa.Column('first_name', sa.String(length=80), nullable=False),
        sa.Column('last_name', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=120), unique=True, nullable=False),
        sa.Column('password_hash', sa.String(length=512), nullable=False),
        sa.Column('image_filename', sa.String(length=200), default='images/profile.png'),
        sa.Column('motivation_message', sa.Text(), nullable=True),
        sa.Column('motivation_date', sa.Date(), nullable=True)
    )

    # Create category table (depends on user)
    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('color', sa.String(length=20), default='#3b82f6'),
        sa.Column('icon', sa.String(length=50), default='fa-folder'),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('archived', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )

    # Create task table (depends on user)
    op.create_table(
        'task',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('completed', sa.Boolean(), default=False),
        sa.Column('completed_date', sa.Date(), nullable=True),
        sa.Column('deleted', sa.Boolean(), default=False),
        sa.Column('deleted_date', sa.Date(), nullable=True),
        sa.Column('priority', sa.String(length=20), nullable=False, default='Medium'),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('category_color', sa.String(length=20), default='grey'),
        sa.Column('category_name', sa.String(length=50), default='Medium')
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_categories',
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
        sa.PrimaryKeyConstraint('task_id', 'category_id')
    )
    # op.drop_table('category_item')  # Skipped: table may not exist in fresh DB
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        # batch_op.drop_index(batch_op.f('name'))  # Skipped: index does not exist in fresh DB
        batch_op.create_foreign_key('fk_category_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('archived')
        batch_op.drop_column('description')
        batch_op.drop_column('icon')
        batch_op.drop_column('user_id')

    op.create_table('category_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('selected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('category_item_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('task_categories')
    # ### end Alembic commands ###
